# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uifactura.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Factura(object):
    def setupUi(self, Factura):
        Factura.setObjectName("Factura")
        Factura.resize(1075, 622)
        Factura.setMinimumSize(QtCore.QSize(1075, 622))
        Factura.setMaximumSize(QtCore.QSize(1075, 622))
        self.centralwidget = QtWidgets.QWidget(Factura)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tablafac = QtWidgets.QTableWidget(self.centralwidget)
        self.tablafac.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tablafac.sizePolicy().hasHeightForWidth())
        self.tablafac.setSizePolicy(sizePolicy)
        self.tablafac.setMinimumSize(QtCore.QSize(1050, 600))
        self.tablafac.setMaximumSize(QtCore.QSize(1050, 600))
        self.tablafac.setSizeIncrement(QtCore.QSize(1016, 407))
        self.tablafac.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablafac.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tablafac.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tablafac.setObjectName("tablafac")
        self.tablafac.setColumnCount(6)
        self.tablafac.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tablafac.setHorizontalHeaderItem(5, item)
        self.tablafac.horizontalHeader().setDefaultSectionSize(169)
        self.tablafac.horizontalHeader().setMinimumSectionSize(120)
        self.verticalLayout.addWidget(self.tablafac)
        Factura.setCentralWidget(self.centralwidget)

        self.retranslateUi(Factura)
        QtCore.QMetaObject.connectSlotsByName(Factura)

    def retranslateUi(self, Factura):
        _translate = QtCore.QCoreApplication.translate
        Factura.setWindowTitle(_translate("Factura", "Factura"))
        item = self.tablafac.horizontalHeaderItem(0)
        item.setText(_translate("Factura", "Numero de factura"))
        item = self.tablafac.horizontalHeaderItem(1)
        item.setText(_translate("Factura", "Sucursal"))
        item = self.tablafac.horizontalHeaderItem(2)
        item.setText(_translate("Factura", "Fecha"))
        item = self.tablafac.horizontalHeaderItem(3)
        item.setText(_translate("Factura", "Dias"))
        item = self.tablafac.horizontalHeaderItem(4)
        item.setText(_translate("Factura", "Monto"))
        item = self.tablafac.horizontalHeaderItem(5)
        item.setText(_translate("Factura", "Balance"))
