# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uipassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 565)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"    background: transparent;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("*{\n"
"    \n"
"    background-image: url(:/pantalla/pantalla/purple_lemaire_channel-scenery_HD_Wallpaper_medium.jpg);\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-image: none;\n"
"}\n"
"\n"
"QStackedWidget{\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("*{\n"
"    background: transparent;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setStyleSheet("*{\n"
"    background: rgba(0, 0, 0, 0.4);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.horizontalLayout_3.addWidget(self.frame_14, 0, QtCore.Qt.AlignLeft)
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    padding: 5px;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(50, 50, 50);\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimizar = QtWidgets.QPushButton(self.frame_13)
        self.minimizar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/blanco/iconos_blancos/minus-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizar.setIcon(icon)
        self.minimizar.setObjectName("minimizar")
        self.horizontalLayout_4.addWidget(self.minimizar)
        self.maximizar = QtWidgets.QPushButton(self.frame_13)
        self.maximizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/blanco/iconos_blancos/maximize-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizar.setIcon(icon1)
        self.maximizar.setObjectName("maximizar")
        self.horizontalLayout_4.addWidget(self.maximizar)
        self.cerrar = QtWidgets.QPushButton(self.frame_13)
        self.cerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/blanco/iconos_blancos/x-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cerrar.setIcon(icon2)
        self.cerrar.setObjectName("cerrar")
        self.horizontalLayout_4.addWidget(self.cerrar)
        self.horizontalLayout_3.addWidget(self.frame_13, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.paginas = QtWidgets.QStackedWidget(self.frame_4)
        self.paginas.setStyleSheet("QFrame{\n"
"    background: rgba(0, 0, 0, 0.4);\n"
"}")
        self.paginas.setObjectName("paginas")
        self.pagina1 = QtWidgets.QWidget()
        self.pagina1.setStyleSheet("*{\n"
"        padding: 15px;\n"
"\n"
"}")
        self.pagina1.setObjectName("pagina1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pagina1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.pagina1)
        self.frame_2.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.pagina1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);    \n"
"    background-color: none;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border-bottom: 3px solid rgb(255, 255, 255);\n"
"    \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.lineusuario = QtWidgets.QLineEdit(self.frame_3)
        self.lineusuario.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineusuario.setFont(font)
        self.lineusuario.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineusuario.setMaxLength(30)
        self.lineusuario.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineusuario.setObjectName("lineusuario")
        self.verticalLayout_6.addWidget(self.lineusuario)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_7 = QtWidgets.QFrame(self.pagina1)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgba(0, 0, 100, 0.6);\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnrecuperar = QtWidgets.QPushButton(self.frame_7)
        self.btnrecuperar.setMinimumSize(QtCore.QSize(300, 75))
        self.btnrecuperar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnrecuperar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnrecuperar.setFont(font)
        self.btnrecuperar.setObjectName("btnrecuperar")
        self.verticalLayout_2.addWidget(self.btnrecuperar, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_7)
        self.paginas.addWidget(self.pagina1)
        self.pagina2 = QtWidgets.QWidget()
        self.pagina2.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgba(0, 0, 100, 0.6);\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.pagina2.setObjectName("pagina2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pagina2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.pagina2)
        self.frame_6.setStyleSheet("QLabel{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: none;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(self.pagina2)
        self.frame_5.setStyleSheet("QLineEdit{\n"
"    font-family: Arial, sans-serif;\n"
"    font-size: 40px;\n"
"    color: rgb(255, 255, 255);\n"
"    border: none;\n"
"    border: 3px solid rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    margin: 5px;\n"
"    width: 100px;\n"
"    height: 100px;\n"
"}\n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.digito1 = QtWidgets.QLineEdit(self.frame_5)
        self.digito1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito1.setInputMask("")
        self.digito1.setMaxLength(1)
        self.digito1.setAlignment(QtCore.Qt.AlignCenter)
        self.digito1.setObjectName("digito1")
        self.horizontalLayout_2.addWidget(self.digito1)
        self.digito2 = QtWidgets.QLineEdit(self.frame_5)
        self.digito2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito2.setInputMask("")
        self.digito2.setMaxLength(1)
        self.digito2.setAlignment(QtCore.Qt.AlignCenter)
        self.digito2.setObjectName("digito2")
        self.horizontalLayout_2.addWidget(self.digito2)
        self.digito3 = QtWidgets.QLineEdit(self.frame_5)
        self.digito3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito3.setInputMask("")
        self.digito3.setMaxLength(1)
        self.digito3.setAlignment(QtCore.Qt.AlignCenter)
        self.digito3.setObjectName("digito3")
        self.horizontalLayout_2.addWidget(self.digito3)
        self.digito4 = QtWidgets.QLineEdit(self.frame_5)
        self.digito4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito4.setInputMask("")
        self.digito4.setMaxLength(1)
        self.digito4.setAlignment(QtCore.Qt.AlignCenter)
        self.digito4.setObjectName("digito4")
        self.horizontalLayout_2.addWidget(self.digito4)
        self.digito5 = QtWidgets.QLineEdit(self.frame_5)
        self.digito5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito5.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito5.setInputMask("")
        self.digito5.setMaxLength(1)
        self.digito5.setAlignment(QtCore.Qt.AlignCenter)
        self.digito5.setObjectName("digito5")
        self.horizontalLayout_2.addWidget(self.digito5)
        self.digito6 = QtWidgets.QLineEdit(self.frame_5)
        self.digito6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.digito6.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.digito6.setInputMask("")
        self.digito6.setMaxLength(1)
        self.digito6.setAlignment(QtCore.Qt.AlignCenter)
        self.digito6.setObjectName("digito6")
        self.horizontalLayout_2.addWidget(self.digito6)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.frame_8 = QtWidgets.QFrame(self.pagina2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btnrestablecer = QtWidgets.QPushButton(self.frame_8)
        self.btnrestablecer.setMinimumSize(QtCore.QSize(199, 100))
        self.btnrestablecer.setMaximumSize(QtCore.QSize(200, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnrestablecer.setFont(font)
        self.btnrestablecer.setObjectName("btnrestablecer")
        self.verticalLayout_8.addWidget(self.btnrestablecer, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addWidget(self.frame_8)
        self.paginas.addWidget(self.pagina2)
        self.pagina3 = QtWidgets.QWidget()
        self.pagina3.setStyleSheet("*{\n"
"        padding: 15px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color: rgba(0, 0, 100, 0.6);\n"
"    border: 3px solid rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}")
        self.pagina3.setObjectName("pagina3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pagina3)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_9 = QtWidgets.QFrame(self.pagina3)
        self.frame_9.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    background-color: none;\n"
"\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_13.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.pagina3)
        self.frame_11.setStyleSheet("\n"
"QLabel{\n"
"    color: white;\n"
"    background-color: none;\n"
"    \n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: none;\n"
"    border:10px;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"    border-bottom: 3px solid rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.nuevaclave1 = QtWidgets.QLineEdit(self.frame_11)
        self.nuevaclave1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.nuevaclave1.setClearButtonEnabled(True)
        self.nuevaclave1.setObjectName("nuevaclave1")
        self.verticalLayout_12.addWidget(self.nuevaclave1)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.nuevaclave2 = QtWidgets.QLineEdit(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.nuevaclave2.setFont(font)
        self.nuevaclave2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.nuevaclave2.setClearButtonEnabled(True)
        self.nuevaclave2.setObjectName("nuevaclave2")
        self.verticalLayout_12.addWidget(self.nuevaclave2)
        self.verticalLayout_10.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.pagina3)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.btnfinalizar = QtWidgets.QPushButton(self.frame_10)
        self.btnfinalizar.setMinimumSize(QtCore.QSize(300, 100))
        self.btnfinalizar.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnfinalizar.setFont(font)
        self.btnfinalizar.setObjectName("btnfinalizar")
        self.verticalLayout_11.addWidget(self.btnfinalizar, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addWidget(self.frame_10)
        self.paginas.addWidget(self.pagina3)
        self.verticalLayout_4.addWidget(self.paginas)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.paginas.setCurrentIndex(0)
        self.lineusuario.returnPressed.connect(self.lineusuario.setFocus) # type: ignore
        self.digito1.textChanged['QString'].connect(self.digito2.setFocus) # type: ignore
        self.digito2.textChanged['QString'].connect(self.digito3.setFocus) # type: ignore
        self.digito3.textChanged['QString'].connect(self.digito4.setFocus) # type: ignore
        self.digito4.textChanged['QString'].connect(self.digito5.setFocus) # type: ignore
        self.digito5.textChanged['QString'].connect(self.digito6.setFocus) # type: ignore
        self.nuevaclave1.returnPressed.connect(self.nuevaclave2.setFocus) # type: ignore
        self.nuevaclave2.returnPressed.connect(self.btnfinalizar.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>My <span style=\" font-weight:600;\">Password</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Recuperacion de clave"))
        self.label_3.setText(_translate("MainWindow", "Inserte el nombre de usuario"))
        self.lineusuario.setPlaceholderText(_translate("MainWindow", "Nombre de usuario"))
        self.btnrecuperar.setText(_translate("MainWindow", "Confirmar cuenta"))
        self.label_9.setText(_translate("MainWindow", "Reset Password"))
        self.label_10.setText(_translate("MainWindow", "Inserte los digitos que hemos enviado a su correo"))
        self.btnrestablecer.setText(_translate("MainWindow", "Restablecer Contraseña"))
        self.label_2.setText(_translate("MainWindow", "Restablecimiento de clave"))
        self.label_4.setText(_translate("MainWindow", "Ingrese los datos para restablecer su clave"))
        self.label_6.setText(_translate("MainWindow", "Inserte la nueva clave"))
        self.nuevaclave1.setPlaceholderText(_translate("MainWindow", "Nuevo Contraseña"))
        self.label_5.setText(_translate("MainWindow", "Confirma la clave"))
        self.nuevaclave2.setPlaceholderText(_translate("MainWindow", "Confirmar clave"))
        self.btnfinalizar.setText(_translate("MainWindow", "Finalizar proceso"))
import iconos