# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uiproducto.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Producto(object):
    def setupUi(self, Producto):
        Producto.setObjectName("Producto")
        Producto.resize(1431, 653)
        Producto.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Producto)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("*{\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame_3, 0, QtCore.Qt.AlignTop)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    height: 25;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    border-radius: 5px;\n"
"    height: 50;    \n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    border: 15px solid rgb(228, 236, 236);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    text-align: center;\n"
"\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(11)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.busnombre = QtWidgets.QLineEdit(self.frame_4)
        self.busnombre.setMinimumSize(QtCore.QSize(300, 0))
        self.busnombre.setMaximumSize(QtCore.QSize(300, 16777215))
        self.busnombre.setObjectName("busnombre")
        self.horizontalLayout_2.addWidget(self.busnombre)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.busprecio = QtWidgets.QLineEdit(self.frame_4)
        self.busprecio.setObjectName("busprecio")
        self.horizontalLayout_2.addWidget(self.busprecio)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.busespec = QtWidgets.QLineEdit(self.frame_4)
        self.busespec.setObjectName("busespec")
        self.horizontalLayout_2.addWidget(self.busespec)
        self.verticalLayout_2.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    height: 25;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    border-radius: 5px;\n"
"    height: 50;    \n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    border: 15px solid rgb(228, 236, 236);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    text-align: center;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tablaproducto = QtWidgets.QTableWidget(self.frame_2)
        self.tablaproducto.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablaproducto.setDragDropOverwriteMode(True)
        self.tablaproducto.setAlternatingRowColors(True)
        self.tablaproducto.setGridStyle(QtCore.Qt.SolidLine)
        self.tablaproducto.setObjectName("tablaproducto")
        self.tablaproducto.setColumnCount(6)
        self.tablaproducto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablaproducto.setHorizontalHeaderItem(5, item)
        self.tablaproducto.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_3.addWidget(self.tablaproducto)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame)
        Producto.setCentralWidget(self.centralwidget)

        self.retranslateUi(Producto)
        QtCore.QMetaObject.connectSlotsByName(Producto)

    def retranslateUi(self, Producto):
        _translate = QtCore.QCoreApplication.translate
        Producto.setWindowTitle(_translate("Producto", "MainWindow"))
        self.label.setText(_translate("Producto", "Producto"))
        self.label_3.setText(_translate("Producto", "Busqueda por nombre"))
        self.label_2.setText(_translate("Producto", "Filtrar Por Precio"))
        self.label_4.setText(_translate("Producto", "Especificacion"))
        item = self.tablaproducto.horizontalHeaderItem(0)
        item.setText(_translate("Producto", "ID del producto"))
        item = self.tablaproducto.horizontalHeaderItem(1)
        item.setText(_translate("Producto", "Nombre del producto"))
        item = self.tablaproducto.horizontalHeaderItem(2)
        item.setText(_translate("Producto", "Punto de retorno"))
        item = self.tablaproducto.horizontalHeaderItem(3)
        item.setText(_translate("Producto", "Cantidad de existencia"))
        item = self.tablaproducto.horizontalHeaderItem(4)
        item.setText(_translate("Producto", "Precio del producto"))
        item = self.tablaproducto.horizontalHeaderItem(5)
        item.setText(_translate("Producto", "Especificacion del producto"))
