# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uirepfac.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabla = QtWidgets.QTreeWidget(self.centralwidget)
        self.tabla.setObjectName("tabla")
        self.tabla.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.tabla.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.tabla.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.tabla.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.tabla.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        self.tabla.header().setMinimumSectionSize(200)
        self.verticalLayout.addWidget(self.tabla)
        self.limpiar = QtWidgets.QPushButton(self.centralwidget)
        self.limpiar.setObjectName("limpiar")
        self.verticalLayout.addWidget(self.limpiar)
        self.imprimir = QtWidgets.QPushButton(self.centralwidget)
        self.imprimir.setObjectName("imprimir")
        self.verticalLayout.addWidget(self.imprimir)
        self.vista = QtWidgets.QPushButton(self.centralwidget)
        self.vista.setObjectName("vista")
        self.verticalLayout.addWidget(self.vista)
        self.cargar = QtWidgets.QPushButton(self.centralwidget)
        self.cargar.setObjectName("cargar")
        self.verticalLayout.addWidget(self.cargar)
        self.exportar = QtWidgets.QPushButton(self.centralwidget)
        self.exportar.setObjectName("exportar")
        self.verticalLayout.addWidget(self.exportar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabla.headerItem().setText(0, _translate("MainWindow", "ID Producto"))
        self.tabla.headerItem().setText(1, _translate("MainWindow", "Cantidad "))
        self.tabla.headerItem().setText(2, _translate("MainWindow", "Precio"))
        self.tabla.headerItem().setText(3, _translate("MainWindow", "ITBIS"))
        self.tabla.headerItem().setText(4, _translate("MainWindow", "Importe"))
        self.limpiar.setText(_translate("MainWindow", "Limpiar Tabla"))
        self.imprimir.setText(_translate("MainWindow", "Imprimir"))
        self.vista.setText(_translate("MainWindow", "Vista Previa"))
        self.cargar.setText(_translate("MainWindow", "Cargar Datos"))
        self.exportar.setText(_translate("MainWindow", "Exportar PDF"))
