# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uisuplidor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Suplidor(object):
    def setupUi(self, Suplidor):
        Suplidor.setObjectName("Suplidor")
        Suplidor.resize(1364, 749)
        self.centralwidget = QtWidgets.QWidget(Suplidor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setStyleSheet("*{\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.frame_6, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.frame_8.setFont(font)
        self.frame_8.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    height: 25;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    border-radius: 5px;\n"
"    height: 50;    \n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    border: 15px solid rgb(228, 236, 236);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    text-align: center;\n"
"\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    color: rgb(0, 0, 0);\n"
"    height: 25;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    border-radius: 5px;\n"
"    height: 50;    \n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    border: 15px solid rgb(228, 236, 236);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(228, 236, 236);\n"
"    text-align: center;\n"
"\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.formLayout = QtWidgets.QFormLayout(self.frame_7)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.nombre = QtWidgets.QLineEdit(self.frame_7)
        self.nombre.setMaximumSize(QtCore.QSize(300, 16777215))
        self.nombre.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nombre.setObjectName("nombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nombre)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.tablasup = QtWidgets.QTableWidget(self.frame_8)
        self.tablasup.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tablasup.setDragDropOverwriteMode(True)
        self.tablasup.setAlternatingRowColors(True)
        self.tablasup.setGridStyle(QtCore.Qt.SolidLine)
        self.tablasup.setObjectName("tablasup")
        self.tablasup.setColumnCount(6)
        self.tablasup.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablasup.setHorizontalHeaderItem(5, item)
        self.tablasup.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout_5.addWidget(self.tablasup)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.horizontalLayout_3.addWidget(self.frame)
        Suplidor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Suplidor)
        QtCore.QMetaObject.connectSlotsByName(Suplidor)

    def retranslateUi(self, Suplidor):
        _translate = QtCore.QCoreApplication.translate
        Suplidor.setWindowTitle(_translate("Suplidor", "MainWindow"))
        self.label_4.setText(_translate("Suplidor", "Suplidor"))
        self.label_5.setText(_translate("Suplidor", "Busqueda por nombre"))
        item = self.tablasup.horizontalHeaderItem(0)
        item.setText(_translate("Suplidor", "ID del suplidor"))
        item = self.tablasup.horizontalHeaderItem(1)
        item.setText(_translate("Suplidor", "Nombre del producto"))
        item = self.tablasup.horizontalHeaderItem(2)
        item.setText(_translate("Suplidor", "Telefono del suplidor"))
        item = self.tablasup.horizontalHeaderItem(3)
        item.setText(_translate("Suplidor", "Direccion del suplidor"))
        item = self.tablasup.horizontalHeaderItem(4)
        item.setText(_translate("Suplidor", "Correo del suplidor"))
        item = self.tablasup.horizontalHeaderItem(5)
        item.setText(_translate("Suplidor", "WEB de la suplidora"))
